name: Build and deploy Node.js app to Azure Web App - newyear-appfront1
on:
  push:
    branches:
      - main  # Branch ที่จะ trigger การ deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set Environment Variables
      run: |
        echo "REACT_APP_API_URL=https://newyear-appback1.azurewebsites.net" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'newyear-appfront1'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './build'
